### ISSUE TITLE
str to glimpse

### ISSUE THREAD

**Issue by statunizaga** [brry/rskey#1]
Hi dude, your package is awesome, just a suggestion may you change str function to glimpse from dplyr.
Because the appareance of glimpse looks better than str function.

**Comment by brry** [comment]
Nice idea, thanks for the suggestion!
I implemented it with an option to be non-intrusive for people without `pillar` installed.

**Comment by statunizaga** [comment]
> Nice idea, thanks for the suggestion! I implemented it with an option to be non-intrusive for people without `pillar` installed.

Thanks, Maybe im wrong, I installed again the new version but it is still using the last function(str)

![image](https://user-images.githubusercontent.com/44730806/182040002-9bcb5e1e-5bb8-4d66-9c37-b65e1c55ef3d.png)

**Comment by brry** [comment]
Did you set the option to TRUE with `options(rskey_glimpse=TRUE)`? 
To set permananently, use: 
`cat("options(rskey_glimpse=TRUE)\n", file="~/.Rprofile", append=TRUE)`

**Comment by statunizaga** [comment]
> Did you set the option to TRUE with `options(rskey_glimpse=TRUE)`? To set permananently, use: `cat("options(rskey_glimpse=TRUE)\n", file="~/.Rprofile", append=TRUE)`

Now Its working, thanks Bro.
